"""
Module for generating sample datasets for testing.
"""

import os
import pandas as pd
import random as rd
import numpy as np
from sklearn.datasets import make_classification
from typing import Tuple

def add_correlation_noise(df: pd.DataFrame, noise_level: float = 0.2) -> pd.DataFrame:
    """Add correlation noise between columns."""
    df_noisy = df.copy()
    for col in df.columns:
        if col not in ['ID', 'YTarget']:  # Skip ID and target columns
            # Add 2% of each other column's values
            for other_col in df.columns:
                if other_col != col and other_col not in ['ID', 'YTarget']:
                    df_noisy[col] += rd.random() *noise_level * df[other_col]
    return df_noisy

def create_synthetic_datasets(n_samples: int = 10_000, n_features: int = 10, 
                               random_state: int = 42) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Create two synthetic datasets with a common ID column and meaningful correlation with the target."""
    
    np.random.seed(random_state)
    
    # Generate unique IDs
    ids = np.arange(1, n_samples + 1)
    
    # Total features generated by sklearn
    n_features_total = n_features * 2 - 2

    # Create classification dataset with some informative and redundant features
    X_class, y_class = make_classification(
        n_samples=n_samples, 
        n_features=n_features_total, 
        n_informative=n_features_total,
        n_redundant=0,
        n_clusters_per_class=2,
        class_sep=1.0,
        flip_y=0.01,
        random_state=random_state
    )

    # Split generated features into df1 (with target) and df2
    features_per_df = n_features_total // 2
    df1 = pd.DataFrame(X_class[:, :features_per_df], 
                       columns=[f'Feature_{i+1}' for i in range(features_per_df)])
    df2 = pd.DataFrame(X_class[:, features_per_df:], 
                       columns=[f'Extra_Feature_{i+1}' for i in range(X_class.shape[1] - features_per_df)])

    # Add meaningful categorical features in df1 based on YTarget
    df1['Gender'] = np.where(y_class == 1, 
                             np.random.choice(['M', 'F'], size=n_samples, p=[0.7, 0.3]), 
                             np.random.choice(['M', 'F'], size=n_samples, p=[0.3, 0.7]))

    df1['Education_Level'] = np.where(y_class == 1, 
                                      np.random.choice(['Bachelor', 'Master', 'PhD'], size=n_samples, p=[0.4, 0.4, 0.2]),
                                      np.random.choice(['High School', 'Bachelor'], size=n_samples, p=[0.6, 0.4]))

    # Add random categorical features in df2
    df2['Employment_Status'] = np.random.choice(['Employed', 'Unemployed', 'Self-employed', 'Student'], 
                                                size=n_samples, p=[0.6, 0.1, 0.2, 0.1])
    df2['Marital_Status'] = np.random.choice(['Single', 'Married', 'Divorced', 'Widowed'], 
                                             size=n_samples, p=[0.4, 0.4, 0.15, 0.05])

    # Add ID and Target columns
    df1['YTarget'] = y_class
    df1['ID'] = ids
    df2['ID'] = ids

    for tabular_type in ['csv', 'excel', 'parquet', 'json']:    
        os.makedirs(f'Datasets/Tabular/Binary_pred/{tabular_type}', exist_ok=True)
    
    # CSV
    df1.to_csv(f'Datasets/Tabular/Binary_pred/csv/dataset1_with_target.csv', index=False)
    df2.to_csv(f'Datasets/Tabular/Binary_pred/csv/dataset2_features_only.csv', index=False)

    # Excel
    df1.to_excel(f'Datasets/Tabular/Binary_pred/excel/dataset1_with_target.xlsx', index=False)
    df2.to_excel(f'Datasets/Tabular/Binary_pred/excel/dataset2_features_only.xlsx', index=False)
    
    # Parquet
    df1.to_parquet(f'Datasets/Tabular/Binary_pred/parquet/dataset1_with_target.parquet', index=False)
    df2.to_parquet(f'Datasets/Tabular/Binary_pred/parquet/dataset2_features_only.parquet', index=False)

    # JSON
    df1.to_json(f'Datasets/Tabular/Binary_pred/json/dataset1_with_target.json', orient='records', lines=True, index=False)
    df2.to_json(f'Datasets/Tabular/Binary_pred/json/dataset2_features_only.json', orient='records', lines=True, index=False)

    print(f"Datasets created successfully:")
    return df1, df2


def create_time_series_dataset(n_samples: int = 10_000, n_features: int = 10, 
                             random_state: int = 42) -> pd.DataFrame:
    """Create a synthetic time series dataset with a 10 step prediction task."""
    # Set random seed for reproducibility
    np.random.seed(random_state)
    
    # Create a dataframe with time index
    dates = pd.date_range(start='2020-01-01', periods=n_samples, freq='D')
    df = pd.DataFrame(index=dates)
    
    # Add ID column
    df['ID'] = np.arange(1, n_samples + 1)
    
    # Create base features with different patterns
    for i in range(n_features):
        # Create a feature with trend
        if i % 3 == 0:
            # Linear trend with some noise
            trend = np.linspace(0, 10, n_samples) + np.random.normal(0, 0.5, n_samples)
            df[f'Feature_{i+1}'] = trend
        # Create a feature with seasonality
        elif i % 3 == 1:
            # Seasonal pattern with different frequencies
            period = 365 if i < 3 else 30 if i < 6 else 7
            seasonality = 5 * np.sin(2 * np.pi * np.arange(n_samples) / period) + np.random.normal(0, 0.3, n_samples)
            df[f'Feature_{i+1}'] = seasonality
        # Create a feature with both trend and seasonality
        else:
            # Combine trend and seasonality
            trend = np.linspace(0, 5, n_samples)
            period = 180 if i < 5 else 90
            seasonality = 3 * np.sin(2 * np.pi * np.arange(n_samples) / period)
            df[f'Feature_{i+1}'] = trend + seasonality + np.random.normal(0, 0.4, n_samples)
    
    # Create target variable that depends on previous values of features
    target = np.zeros(n_samples)
    
    for i in range(10, n_samples):
        # Target depends on the last 10 values of the first 3 features with decreasing weights
        weights = np.array([0.8, 0.6, 0.4, 0.3, 0.2, 0.1, 0.05, 0.05, 0.05, 0.05])
        
        for j in range(3):  # Use only first 3 features for simplicity
            feature_values = df[f'Feature_{j+1}'].values[i-10:i]
            target[i] += np.sum(feature_values * weights)
        
        # Add some noise
        target[i] += np.random.normal(0, 1.0)
    
    # Add target to dataframe
    df['Target'] = target

    # Drop Index 
    df = df.reset_index(drop=True)

    # Drop first 10 rows
    df = df.iloc[10:]

    # Create directory if it doesn't exist
    os.makedirs('Datasets/Tabular/Time_series', exist_ok=True)
    
    # Save dataset
    for tabular_type in ['csv', 'excel', 'parquet', 'json']:
        os.makedirs(f'Datasets/Tabular/Time_series/{tabular_type}', exist_ok=True)

    df.to_csv(f'Datasets/Tabular/Time_series/csv/dataset_time_series.csv', index=True)
    df.to_excel(f'Datasets/Tabular/Time_series/excel/dataset_time_series.xlsx', index=True)
    df.to_parquet(f'Datasets/Tabular/Time_series/parquet/dataset_time_series.parquet', index=True)
    df.to_json(f'Datasets/Tabular/Time_series/json/dataset_time_series.json', orient='records', lines=True, index=False)

    print(f"Time series dataset created successfully:")    
    return df

if __name__ == "__main__":
    create_synthetic_datasets()
    create_time_series_dataset() 